"""empty message

Revision ID: d66ce872585a
Revises: b69e358a0ea9
Create Date: 2021-08-25 12:19:44.035336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66ce872585a'
down_revision = 'b69e358a0ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('cabinId', sa.Integer(), nullable=True),
    sa.Column('checkin', sa.Date(), nullable=True),
    sa.Column('checkout', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cabinId'], ['cabins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('cabinId', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['cabinId'], ['cabins.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('bookings')
    # ### end Alembic commands ###
